# Generated by Django 4.2.7 on 2024-12-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_user_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='index_num',
        ),
    ]
